import React, { useState } from 'react';
import { Sparkles, Heart, Loader2, RefreshCw } from 'lucide-react';
import { generateRomanticPoem } from '../services/geminiService';
import { GeneratedPoem, AppState } from '../types';

const LoveNoteGenerator: React.FC = () => {
  const [poem, setPoem] = useState<GeneratedPoem | null>(null);
  const [appState, setAppState] = useState<AppState>(AppState.IDLE);

  const handleGenerate = async () => {
    setAppState(AppState.GENERATING);
    try {
      const result = await generateRomanticPoem();
      setPoem(result);
      setAppState(AppState.SUCCESS);
    } catch (e) {
      setAppState(AppState.ERROR);
    }
  };

  return (
    <div className="absolute top-10 left-1/2 transform -translate-x-1/2 z-20 w-full max-w-md px-4">
      <div className="bg-slate-900/40 backdrop-blur-md border border-white/10 rounded-2xl p-6 shadow-2xl text-center">
        
        {appState === AppState.IDLE && (
          <div className="space-y-4">
            <h1 className="text-3xl text-white font-[DancingScript] mb-2" style={{ fontFamily: 'Dancing Script, cursive' }}>
              Make a Wish
            </h1>
            <p className="text-slate-300 text-sm mb-6">
              As meteors streak across the sky, capture the moment with a poem generated by the stars.
            </p>
            <button
              onClick={handleGenerate}
              className="group relative inline-flex items-center justify-center px-8 py-3 text-lg font-medium text-white bg-indigo-600 rounded-full hover:bg-indigo-700 transition-all duration-300 ease-in-out hover:scale-105 hover:shadow-[0_0_20px_rgba(79,70,229,0.5)]"
            >
              <Sparkles className="w-5 h-5 mr-2 animate-pulse" />
              <span>Capture the Moment</span>
            </button>
          </div>
        )}

        {appState === AppState.GENERATING && (
          <div className="py-8 flex flex-col items-center justify-center">
            <Loader2 className="w-10 h-10 text-indigo-400 animate-spin mb-4" />
            <p className="text-indigo-200 animate-pulse">Consulting the stars...</p>
          </div>
        )}

        {appState === AppState.SUCCESS && poem && (
          <div className="animate-fade-in-up">
            <h2 className="text-2xl text-indigo-300 font-serif mb-4 font-bold tracking-wide">
              {poem.title}
            </h2>
            <div className="relative mb-6">
              <Heart className="absolute -top-4 -left-2 w-6 h-6 text-pink-500/50 animate-bounce" />
              <p className="text-slate-100 whitespace-pre-line leading-relaxed font-serif text-lg italic opacity-90">
                {poem.content}
              </p>
              <Heart className="absolute -bottom-4 -right-2 w-6 h-6 text-pink-500/50 animate-bounce delay-75" />
            </div>
            
            <button
              onClick={handleGenerate}
              className="mt-4 flex items-center justify-center mx-auto text-sm text-indigo-400 hover:text-indigo-300 transition-colors"
            >
              <RefreshCw className="w-4 h-4 mr-2" />
              Another Wish
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default LoveNoteGenerator;
